spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ecomtask_db:5432/ecomtask
    username: ecom_user
    password: qwerty123
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
server:
  port: 8080