spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:ecomtask_test
    driverClassName: org.h2.Driver
    username: sa
    password: ""
#      url: jdbc:postgresql://localhost:9601/ecomtask
#      username: ecom_user
#      driverClassName: org.postgresql.Driver
#      password: qwerty123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
server:
  port: 8080